In [1]:
import numpy as np
np.__version__

'2.1.3'

In [3]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
zeros = np.zeros((2, 3)) #creates a 2x3 array filled with zeros
ones = np.ones((3, 2))
rand = np.random.rand(2, 3)

for x in [a, b, zeros, ones, rand]:
    print(type(x), x.shape, x.dtype)

<class 'numpy.ndarray'> (3,) int64
<class 'numpy.ndarray'> (2, 2) int64
<class 'numpy.ndarray'> (2, 3) float64
<class 'numpy.ndarray'> (3, 2) float64
<class 'numpy.ndarray'> (2, 3) float64


In [5]:
v = np.array([10, 20, 30, 40, 50])
print(v[0], v[-1]) #first and last element
print(v[1:4]) #slice element(2-4)

m = np.array([[1, 2, 3], 
             [4, 5, 6],
             [7, 8, 9]])

print(m[0, 2]) #row 0, col 2 -> 3
print(m[:, 1]) # all rows, col 1 -> [2, 5, 8]

#boolean masking
mask = v > 25
print(mask) # [False, False, True, True, True]
print(v[mask]) # [30 40 50]

10 50
[20 30 40]
3
[2 5 8]
[False False  True  True  True]
[30 40 50]


In [7]:
x = np.arange(1, 6)

# Regular loop (slow)
total_loop = 0
for n in x:
    total_loop += n**2

# Vectorized (fast)
total_vec = np.sum(x**2)
print(total_loop, total_vec)

55 55


In [8]:
A = np.ones((3, 4))
row = np.array([1, 2, 3, 4])
col = np.array([[10], [20], [30]])

print(A + row) #adds row to each row (3x4)
print(A + col) #adds col to each column (3x4)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [10]:
X = np.array([[2, 4, 6], 
             [1, 3, 5]])

print(X.sum()) 
print(X.sum(axis=0)) #sum each column -> [3 7 11]
print(X.mean(axis=0)) #average per column
print(X.mean(axis=1)) #average per row -> [4. 3.]

print(np.min(X), np.max(X), np.median(X), np.std(X))
#axis = 0 means "down columns"; axis = 1 means "across rows."

21
[ 3  7 11]
[1.5 3.5 5.5]
[4. 3.]
1 6 3.5 1.707825127659933


In [12]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print("dot:", np.dot(u, v)) #dot product = 1*4 + 2*5 + 3*6 = 32

M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
print("matrix multiply:\n", M @ N) #@ = matrix multiplication
print("transpose:\n", M.T)

dot: 32
matrix multiply:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]


In [14]:
z = np.array([1, 2, 3], dtype=np.int32)
print(z.dtype)

z = z.astype(np.float64)
print(z.dtype)
#you can convert types anytime using .astype()

int32
float64


In [15]:
rng = np.random.default_rng(seed = 42) #fixed seed -> same result every run
samples = rng.normal(loc = 0, scale = 1, size = (2,3))
print(samples)

[[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]]


In [18]:
#practice
arr = np.arange(1, 101)
print(np.mean(arr))
mask = arr % 7 == 0
print(mask)

50.5
[False False False False False False  True False False False False False
 False  True False False False False False False  True False False False
 False False False  True False False False False False False  True False
 False False False False False  True False False False False False False
  True False False False False False False  True False False False False
 False False  True False False False False False False  True False False
 False False False False  True False False False False False False  True
 False False False False False False  True False False False False False
 False  True False False]


In [19]:
arr = np.arange(100)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [20]:
matrix = arr.reshape(10, 10)
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [21]:
diagonal = np.diag(matrix)
print(diagonal)

[ 0 11 22 33 44 55 66 77 88 99]


In [25]:
mean_column = matrix.mean(axis = 0)
print(mean_column)

[45. 46. 47. 48. 49. 50. 51. 52. 53. 54.]


In [27]:
A = np.random.rand(3, 4)
b = np.random.rand(4)

print(A)
print(b)

[[0.3903278  0.55914585 0.01582465 0.26623445]
 [0.582281   0.75284982 0.55602807 0.57445247]
 [0.54186114 0.30053739 0.2550704  0.59361557]]
[0.22640783 0.20417744 0.79434972 0.75218684]


In [29]:
result = A @ b
print(result)

[0.4153666  1.15932426 0.83316948]


In [30]:
data = np.random.rand(100, 3)
print(data.shape)

(100, 3)


In [33]:
col_means = data.mean(axis=0)
col_stds = data.std(axis=0)
print("Column Means:", col_means)
print("Column STDs:", col_stds)

Column Means: [0.48686267 0.56295351 0.45085043]
Column STDs: [0.27685064 0.25259288 0.26755456]
